---
# Source: coroot/charts/prometheus/templates/server/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    component: "server"
    app: prometheus
    release: coroot
    chart: prometheus-15.16.1
    heritage: Helm
  name: coroot-prometheus-server
  namespace: coroot
  annotations:
    {}
