namespace: coroot
resources:
- 00-ns.yaml
- coroot/charts/clickhouse/templates/service-account.yaml
- coroot/charts/prometheus/charts/kube-state-metrics/templates/serviceaccount.yaml
- coroot/charts/prometheus/templates/server/serviceaccount.yaml
- coroot/templates/cluster-agent.yaml
- coroot/templates/serviceaccount.yaml
- coroot/charts/clickhouse/templates/secret.yaml
- coroot/charts/clickhouse/templates/configmap-extra.yaml
- coroot/charts/clickhouse/templates/configmap.yaml
- coroot/charts/clickhouse/templates/scripts-configmap.yaml
- coroot/charts/prometheus/templates/server/cm.yaml
- coroot/charts/prometheus/templates/server/pvc.yaml
- coroot/templates/pvc.yaml
- coroot/charts/prometheus/charts/kube-state-metrics/templates/role.yaml
- coroot/charts/prometheus/templates/server/clusterrole.yaml
- coroot/charts/prometheus/charts/kube-state-metrics/templates/clusterrolebinding.yaml
- coroot/charts/prometheus/templates/server/clusterrolebinding.yaml
- coroot/charts/clickhouse/templates/service-headless.yaml
- coroot/charts/clickhouse/templates/service.yaml
- coroot/charts/prometheus/charts/kube-state-metrics/templates/service.yaml
- coroot/charts/prometheus/templates/server/service.yaml
- coroot/templates/service.yaml
- coroot/charts/node-agent/templates/daemonset.yaml
- coroot/charts/prometheus/charts/kube-state-metrics/templates/deployment.yaml
- coroot/charts/prometheus/templates/server/deploy.yaml
- coroot/templates/deployment.yaml
- coroot/charts/clickhouse/templates/statefulset.yaml
- 04-ingress.yaml
