---
# Source: coroot/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: coroot
  labels:
    helm.sh/chart: coroot-0.18.14
    app.kubernetes.io/name: coroot
    app.kubernetes.io/instance: coroot
    app.kubernetes.io/version: "1.8.12"
    app.kubernetes.io/managed-by: Helm
